<a href="https://colab.research.google.com/github/maielhadad99/first/blob/master/numpymini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
lst = [10, 200, 90, 0]

import numpy as np
arr = np.array(lst)

print(arr + 10)

[ 20 210 100  10]


In [3]:
lst = [22, 45, 78, 50]

import numpy as np
import sys
arr = np.array(lst)
print(arr.nbytes)
print(sys.getsizeof(lst))                 

32
104


In [4]:
import numpy as np
a = np.array([1,2,3,4])               # creates a 1-dimensional array
b = np.array([[1,2,3,4], [5,6,7,8]])    # creates a 2-dimensional array
print(a)
print('----')
print(b)

[1 2 3 4]
----
[[1 2 3 4]
 [5 6 7 8]]


In [5]:
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4], [5,6,7,8]])

print('The shape of the array a is ', a.shape)
print('The shape of the array b is ', b.shape)

The shape of the array a is  (4,)
The shape of the array b is  (2, 4)


In [6]:
print('The dimensions of array a is ', a.ndim)
print('The dimensions of array b is ', b.ndim)


The dimensions of array a is  1
The dimensions of array b is  2


In [7]:
print('The size of the array a is ', a.size)
print('The size of the array b is ', b.size)

The size of the array a is  4
The size of the array b is  8


In [8]:
print('The datatype of the array a is ', a.dtype)
print('The datatype of the array b is ', b.dtype)

The datatype of the array a is  int64
The datatype of the array b is  int64


In [9]:
print('The number of bytes in each element of the array a is  ', a.itemsize)
print('The number of bytes in each element of the array b is ', b.itemsize)

The number of bytes in each element of the array a is   8
The number of bytes in each element of the array b is  8


In [10]:
print(np.array([5,6,8,45,12,52]).reshape(2,3))

[[ 5  6  8]
 [45 12 52]]


In [11]:
print(np.matrix([[1,2],[3,4]]))

[[1 2]
 [3 4]]


In [12]:
print(np.eye(3)) # Identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
print( np.zeros( (4,3) ) )


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# NumPy array from 1 to 19
print(np.arange(1,20,dtype='int32'))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
# NumPy array from 1 to 19 with step size 2
print(np.arange(1,20,2,dtype='int8'))

[ 1  3  5  7  9 11 13 15 17 19]


In [16]:
print(np.ones( (3,3), dtype = np.float64 ))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
print(np.array([5,6,8,45,12,52]).reshape(2,3))

[[ 5  6  8]
 [45 12 52]]


In [18]:
print(np.matrix([[1,2],[3,4]]))

[[1 2]
 [3 4]]


In [19]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Pull out second element of third row
print(a[0][2]) # index 0 row and then 1 and 2 
print('==========')
# Pull out first two rows and columns
print(a[:2,:2])
print('==========')
# Pull all elements of the third row
print(a[2,:])

3
[[1 2]
 [4 5]]
[7 8 9]


In [20]:
a=np.array([[1,2],[3,4],[5,6]])

print(a[[0,1,2],[0,1,0]])
print('==========')

print(np.array([a[0,0],a[1,1],a[2,0]]))
print('==========')

print(a[[0,0],[1,1]])
print('==========')

print(np.array([a[0,1],a[0,1]]))
#Explanation: The print statements 1 & 2 and 3 & 4 yield the same results.
 #In the first case, a[[0, 1, 2], [0, 1, 0]] essentially means
  #we are indexing the value in first row-first column, 
  #second row-second column and third row-first column, 
  #which is the same as a[0, 0], a[1, 1], a[2, 0]]. Similarly,
   #you should be able to deduce the logic behind the second case.

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [21]:
a = np.array([[4,7,1],[2,5,7],[7,1,1]])

# Boolean condition for values greater than 3
k = a > 3
print(k)

# Masking for the above boolean condition in the array
print(a[k])

[[ True  True False]
 [False  True  True]
 [ True False False]]
[4 7 5 7 7]


In [22]:
b = ([3,4.5,3+5j,0])
print(np.isreal(b))
print(b)
print(np.iscomplex(b))

[ True  True False  True]
[3, 4.5, (3+5j), 0]
[False False  True False]


In [23]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[arr > 2])

[3 4 5 6 7]


In [24]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,11,12],[13,14,15],[16,17,18]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(np.add(a,b))
a = np.array([[1,4,9],[16,25,36]])
print(np.sqrt(a))


[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]
[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[1. 2. 3.]
 [4. 5. 6.]]


In [25]:
coefficients =  np.array([1,-4,4])
roots = np.roots(coefficients)
print(roots)

[2. 2.]


In [26]:
a = np.array([5,6,7,8])
b = np.array([5,6,7,8])
print(np.array_equal(a,b))

True


In [27]:
a = np.array([[2,5,7],[4,25,30]])

# computes sum over columns
print(a.sum(axis=0))
print('==========')

# computes sum over rows
print(a.sum(axis=1))
print('==========')

# computes total sum
print(a.sum())

[ 6 30 37]
[14 59]
73


In [56]:
#mini project
a= np.array ()

TypeError: ignored

In [30]:
data_file ='/content/makeSenseOfCensus.csv'
data = np.genfromtxt(data_file, delimiter=",", skip_header=1)

In [31]:
print("\nData: \n\n", data)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [32]:
print("\nType of data: \n\n", type(data))


Type of data: 

 <class 'numpy.ndarray'>


In [33]:
print("\nData: \n\n", data)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [34]:
new_record= np.array([[50, 9, 4, 1, 0, 0, 40, 0]], dtype="float") 
print(new_record)
np.concatenate((new_record,data))

[[50.  9.  4.  1.  0.  0. 40.  0.]]


array([[50.,  9.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       ...,
       [48., 13.,  4., ...,  0., 58.,  1.],
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.]])

In [35]:
age=np.array(data[:,0])
print(age)

[39. 50. 38. 53. 28. 37. 49. 52. 31. 42. 37. 30. 23. 32. 40. 34. 25. 32.
 38. 43. 40. 54. 35. 43. 59. 56. 19. 54. 39. 49. 23. 20. 45. 30. 22. 48.
 21. 19. 31. 48. 31. 53. 24. 49. 25. 57. 53. 44. 41. 29. 25. 18. 47. 50.
 47. 43. 46. 35. 41. 30. 30. 32. 48. 42. 29. 36. 28. 53. 49. 25. 19. 31.
 29. 23. 79. 27. 40. 67. 18. 31. 18. 52. 46. 59. 44. 53. 49. 33. 30. 43.
 57. 37. 28. 30. 34. 29. 48. 37. 48. 32. 76. 44. 47. 20. 29. 32. 17. 30.
 31. 42. 24. 38. 56. 28. 36. 53. 56. 49. 55. 22. 21. 40. 30. 29. 19. 47.
 20. 31. 35. 39. 28. 24. 38. 37. 46. 38. 43. 27. 20. 49. 61. 27. 19. 45.
 70. 31. 22. 36. 64. 43. 47. 34. 33. 21. 52. 48. 23. 71. 29. 42. 68. 25.
 44. 28. 45. 36. 39. 46. 18. 66. 27. 28. 51. 27. 28. 27. 21. 34. 18. 33.
 44. 43. 30. 40. 37. 34. 41. 53. 31. 58. 38. 24. 41. 47. 41. 23. 36. 40.
 35. 24. 26. 19. 51. 42. 37. 18. 36. 35. 58. 17. 44. 37. 35. 60. 54. 37.
 50. 38. 45. 25. 31. 64. 90. 54. 53. 18. 60. 66. 75. 65. 35. 41. 25. 33.
 28. 59. 40. 41. 38. 23. 40. 41. 24. 20. 38. 56. 58

In [36]:
max_age = max(age)
print(max_age)

90.0


In [37]:
min_age = min(age)
print(min_age)

17.0


In [38]:
mean_age = np.mean(age)
print(mean_age)

38.051


In [39]:
std_age = np.std(age)
print(std_age)

13.342803266180612


In [40]:
Race=np.array(data[:,2])
print(Race)

[4. 4. 4. 2. 2. 4. 2. 4. 4. 4. 2. 1. 4. 2. 1. 0. 4. 4. 4. 4. 4. 2. 2. 4.
 4. 4. 4. 1. 4. 4. 4. 2. 4. 4. 2. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 4. 4.
 4. 4. 3. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 1. 4. 4.
 4. 4. 4. 2. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 4. 4.
 4. 4. 2. 4. 2. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 4. 4. 4. 4. 1. 4. 4. 4. 4.
 4. 2. 4. 4. 4. 4. 4. 4. 1. 4. 4. 4. 4. 2. 4. 2. 4. 4. 1. 1. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 2. 2. 4. 4. 2. 4. 2. 4. 4. 2. 4. 4. 4. 4. 2. 4.
 2. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 4. 4. 4. 2. 4. 0. 1. 4. 2.
 4. 4. 4. 4. 4. 4. 2. 2. 4. 4. 0. 4. 4. 4. 2. 2. 4. 3. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 2. 4. 4. 1. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 1. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 4. 4. 4. 4. 4. 4. 2. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 2. 4. 4. 1. 4. 4. 4. 1. 4. 4. 1. 4. 4. 4. 4. 4. 4. 1.
 2. 2. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 2. 4. 4.

In [41]:
race_0=data[data[:,2]==0]
len_0=len(race_0)
print(len_0)

10


In [42]:
race_1=data[data[:,2]==1]
len_1=len(race_1)
print(len_1)

27


In [43]:
race_2=data[data[:,2]==2]
len_2=len(race_2)
print(len_2)

110


In [44]:
race_3=data[data[:,2]==3]
len_3=len(race_3)
print(len_3)


6


In [45]:
race_4=data[data[:,2]==4]
len_4=len(race_4)
print(len_4)

847


The Race 3 is the minority

In [46]:
minority_race=len(race_3)
print(minority_race)

6


In [47]:
senior_citizens=data[age>60]

In [48]:

senior_citizens_len=len(senior_citizens)
len(senior_citizens)

61

In [ ]:

senior_citizens=data[data[:,0]>60]
print(senior_citizens)


In [50]:
working_hours_sum=np.sum(senior_citizens[:,6])
print(working_hours_sum)

1917.0


In [51]:
avg_working_hours=np.divide(working_hours_sum,senior_citizens_len)
print(avg_working_hours)

31.42622950819672


The government policy is not followed


In [52]:
high=data[data[:,1]>10]
print(high)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [28. 13.  2. ...  0. 40.  0.]
 ...
 [45. 14.  4. ...  0. 45.  0.]
 [48. 13.  4. ...  0. 58.  1.]
 [39. 13.  4. ...  0. 50.  1.]]


In [53]:
low=data[data[:,2]<=10]
print(low)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [54]:
avg_pay_high=np.mean(high[:,7])
print(avg_pay_high)

0.42813455657492355


In [55]:
avg_pay_low=np.mean(low[:,7])
print(avg_pay_low)

0.232


Yes the higher educated peopple have better pay in general